# Generated by Django 3.1.12 on 2021-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist of name')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Artist Embedding')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Artist Image Url')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
