# Generated by Django 3.1.12 on 2021-06-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='method',
            field=models.CharField(choices=[('Closest Artist', 'Closest Artist'), ('Closest Cluster', 'Closest Cluster')], default='Closest Artist', max_length=120, verbose_name='Recommendation Method'),
        ),
    ]
